#retriever
from retriever.lib.templates import BasicTextTemplate
from retriever.lib.models import Table, Cleanup, correct_invalid_value

SCRIPT = BasicTextTemplate(tables={'Stake_info': Table('Stake_info', cleanup=Cleanup(correct_invalid_value, nulls=['NA', 'nd'])),'SMDensity': Table('SMDensity', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'Plot_corners': Table('Plot_corners', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'Count1906': Table('Count1906', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'Photo_info': Table('Photo_info', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'Seedling_counts': Table('Seedling_counts', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'Plots': Table('Plots', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'SMCover': Table('SMCover', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'Species': Table('Species', cleanup=Cleanup(correct_invalid_value, nulls=['NA']))},
                           description="The data set constitutes all information associated with the Spalding-Shreve permanent vegetation plots from 1906 through 2012, which is the longest-running plant monitoring program in the world.",
                           tags=['Taxon > Plants'],
                           citation="Susana Rodriguez-Buritica, Helen Raichle, Robert H. Webb, Raymond M. Turner, and D. Lawrence Venable. 2013. One hundred and six years of population and community dynamics of Sonoran Desert Laboratory perennials. Ecology 94:976.",
                           urls={'Stake_info': 'http://esapubs.org/archive/ecol/E094/083/Stake_info.csv', 'SMDensity': 'http://esapubs.org/archive/ecol/E094/083/SMDensity.csv', 'Plot_corners': 'http://esapubs.org/archive/ecol/E094/083/Plot_corners.csv', 'Count1906': 'http://esapubs.org/archive/ecol/E094/083/Count1906.csv', 'Photo_info': 'http://esapubs.org/archive/ecol/E094/083/Photo_info.csv', 'Seedling_counts': 'http://esapubs.org/archive/ecol/E094/083/Seedling_counts.csv', 'Plots': 'http://esapubs.org/archive/ecol/E094/083/Plots.csv', 'SMCover': 'http://esapubs.org/archive/ecol/E094/083/SMCover.csv', 'Species': 'http://esapubs.org/archive/ecol/E094/083/Species.csv'},
                           shortname="SonoranPerennials",
                           name="Sonoran Desert Perennials")