#retriever
from retriever.lib.templates import BasicTextTemplate
from retriever.lib.models import Table, Cleanup, correct_invalid_value

SCRIPT = BasicTextTemplate(tables={'quad_info': Table('quad_info', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'allrecords_density': Table('allrecords_density', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'quad_inventory': Table('quad_inventory', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'species_list': Table('species_list', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'quad_stocking_rate': Table('quad_stocking_rate', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'daily_climate': Table('daily_climate', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'species_name_changes': Table('species_name_changes', cleanup=Cleanup(correct_invalid_value, nulls=['NA'])),'allrecords_cover': Table('allrecords_cover', cleanup=Cleanup(correct_invalid_value, nulls=['NA']))},
                           description='This data set maps and analyzes demographic rates of many common plant species in the shortgrass steppe of North America under grazed and ungrazed conditions.',
                           tags=['Taxon > Plants', 'Spatial Scale > Local', 'Data Type > Time Series', 'Data Type > Observational'],
                           citation='Cover, density, and demographics of shortgrass steppe plants mapped 1997-2010 in permanent grazed and ungrazed quadrats. Chengjin Chu, John Norman, Robert Flynn, Nicole Kaplan, William K. Lauenroth, and Peter B. Adler. Ecology 2013 94:6, 1435-1435.',
                           urls={'allrecords_cover': 'http://esapubs.org/archive/ecol/E094/128/allrecords_cover.csv', 'quad_stocking_rate': 'http://esapubs.org/archive/ecol/E094/128/quad_stocking_rate.csv', 'allrecords_density': 'http://esapubs.org/archive/ecol/E094/128/allrecords_density.csv', 'quad_inventory': 'http://esapubs.org/archive/ecol/E094/128/quad_inventory.csv', 'quad_info': 'http://esapubs.org/archive/ecol/E094/128/quad_info.csv', 'daily_climate': 'http://esapubs.org/archive/ecol/E094/128/daily_climate_data.csv', 'species_name_changes': 'http://esapubs.org/archive/ecol/E094/128/species_name_changes.csv', 'species_list': 'http://esapubs.org/archive/ecol/E094/128/species_list.csv'},
                           shortname='Steppe_plants_2013',
                           ref='http://www.esajournals.org/doi/abs/10.1890/13-0121.1',
                           name='Shortgrass steppe plants.')