#retriever
from retriever.lib.templates import BasicTextTemplate
from retriever.lib.models import Table, Cleanup, correct_invalid_value

SCRIPT = BasicTextTemplate(tables={'macroplots': Table('macroplots', ct_names=['TreeGirth1', 'TreeGirth2', 'TreeGirth3', 'TreeGirth4', 'TreeGirth5'],delimiter='	',columns=[('record_id', ('pk-auto',)), ('PlotID', ('char', '20')), ('SpCode', ('char', '30')), ('Girth', ('ct-int',))],ct_column='Tree'),'microplots': Table('microplots', ct_names=['BSP1', 'BSP2', 'BSP3', 'BSP4', 'BSP5', 'BSP6', 'BSP7', 'BSP8', 'BSP9', 'BSP10', 'BSP11', 'BSP12', 'BSP13', 'BSP14', 'BSP15', 'BSP16', 'BSP17', 'BSP18', 'BSP20', 'BSP21', 'BSP22', 'BSP23', 'BSP24', 'BSP25', 'BSP26', 'BSP27', 'BSP28', 'BSP29', 'BSP30', 'BSP31', 'BSP33', 'BSP34', 'BSP35', 'BSP36', 'BSP37', 'BSP41', 'BSP42', 'BSP43', 'BSP44', 'BSP45', 'BSP46', 'BSP47', 'BSP48', 'BSP49', 'BSP50', 'BSP51', 'BSP52', 'BSP53', 'BSP54', 'BSP55', 'BSP56', 'BSP57', 'BSP58', 'BSP59', 'BSP60', 'BSP61', 'BSP62', 'BSP63', 'BSP64', 'BSP65', 'BSP66', 'BSP67', 'BSP68', 'BSP69', 'BSP70', 'BSP71', 'BSP72', 'BSP73', 'BSP74', 'BSP75', 'BSP76', 'BSP78', 'BSP79', 'BSP80', 'BSP82', 'BSP83', 'BSP84', 'BSP85', 'BSP86', 'BSP87', 'BSP88', 'BSP89', 'BSP90', 'BSP91', 'BSP92', 'BSP93', 'BSP94', 'BSP95', 'BSP96', 'BSP97', 'BSP98', 'BSP99', 'BSP100', 'BSP101', 'BSP102', 'BSP104'],delimiter='	',columns=[('record_id', ('pk-auto',)), ('SpCode', ('char', '30')), ('Count', ('ct-int',))],ct_column='PlotID'),'species': Table('species', cleanup=Cleanup(correct_invalid_value, nulls=['NA']))},
                           description='This data set reports woody plant species abundances in a network of 96 sampling sites spread across 22000 km2 in central Western Ghats region, Karnataka, India.',
                           tags=['Taxon > Plants', 'Spatial Scale > Regional', 'Data Type > Observational'],
                           citation='B. R. Ramesh, M. H. Swaminath, Santoshgouda V. Patil, Dasappa, Raphael Pelissier, P. Dilip Venugopal, S. Aravajy, Claire Elouard, and S. Ramalingam. 2010. Forest stand structure and composition in 96 sites along environmental gradients in the central Western Ghats of India. Ecology 91:3118.',
                           urls={'sites': 'http://esapubs.org/archive/ecol/E091/216/Site_variables.txt', 'macroplots': 'http://esapubs.org/archive/ecol/E091/216/Macroplot_data.txt', 'species': 'http://esapubs.org/archive/ecol/E091/216/Species_list.txt', 'microplots': 'http://esapubs.org/archive/ecol/E091/216/Microplot_data.txt'},
                           shortname='Ramesh2010',
                           name='Indian Forest Stand Structure (Ecological Archives 2010)')