# -*- coding: latin-1  -*-
#retriever
from retriever.lib.templates import BasicTextTemplate
from retriever.lib.models import Table, Cleanup, correct_invalid_value

SCRIPT = BasicTextTemplate(tables={'regions': Table('regions', columns=[(u'id', (u'int',)), (u'code', (u'char',)), (u'local_code', (u'char',)), (u'name', (u'char',)), (u'continent', (u'char',)), (u'iso_country', (u'char',)), (u'wikipedia_link', (u'char',)), (u'keywords', (u'char',))]),'airports': Table('airports', columns=[(u'id', (u'int',)), (u'ident', (u'char',)), (u'type', (u'char',)), (u'name', (u'char',)), (u'latitude_deg', (u'double',)), (u'longitude_deg', (u'double',)), (u'elevation_ft', (u'int',)), (u'continent', (u'char',)), (u'iso_country', (u'char',)), (u'iso_region', (u'char',)), (u'municipality', (u'char',)), (u'scheduled_service', (u'char',)), (u'gps_code', (u'char',)), (u'iata_code', (u'char',)), (u'local_code', (u'char',)), (u'home_link', (u'char',)), (u'wikipedia_link', (u'char',)), (u'keywords', (u'char',))]),'countries': Table('countries', columns=[(u'id', (u'int',)), (u'code', (u'char',)), (u'name', (u'char',)), (u'continent', (u'char',)), (u'wikipedia_link', (u'char',)), (u'keywords', (u'char',))]),'runways': Table('runways', columns=[(u'id', (u'int',)), (u'airport_ref', (u'int',)), (u'airport_ident', (u'char',)), (u'length_ft', (u'int',)), (u'width_ft', (u'int',)), (u'surface', (u'char',)), (u'lighted', (u'int',)), (u'closed', (u'int',)), (u'le_ident', (u'char',)), (u'le_latitude_deg', (u'double',)), (u'le_longitude_deg', (u'double',)), (u'le_elevation_ft', (u'int',)), (u'le_heading_degT', (u'double',)), (u'le_displaced_threshold_ft', (u'int',)), (u'he_ident', (u'char',)), (u'he_latitude_deg', (u'double',)), (u'he_longitude_deg', (u'double',)), (u'he_elevation_ft', (u'int',)), (u'he_heading_degT', (u'double',)), (u'he_displaced_threshold_ft', (u'int',))]),'airport_frequencies': Table('airport_frequencies', columns=[(u'id', (u'int',)), (u'airport_ref', (u'int',)), (u'airport_ident', (u'char',)), (u'type', (u'char',)), (u'description', (u'char',)), (u'frequency_mhz', (u'double',))]),'navaids': Table('navaids', columns=[(u'id', (u'int',)), (u'filename', (u'char',)), (u'ident', (u'char',)), (u'name', (u'char',)), (u'type', (u'char',)), (u'frequency_khz', (u'int',)), (u'latitude_deg', (u'double',)), (u'longitude_deg', (u'double',)), (u'elevation_ft', (u'int',)), (u'iso_country', (u'char',)), (u'dme_frequency_khz', (u'int',)), (u'dme_channel', (u'char',)), (u'dme_latitude_deg', (u'double',)), (u'dme_longitude_deg', (u'double',)), (u'dme_elevation_ft', (u'int',)), (u'slaved_variation_deg', (u'double',)), (u'magnetic_variation_deg', (u'double',)), (u'usageType', (u'char',)), (u'power', (u'char',)), (u'associated_airport', (u'char',))])},
                           version="1.0.3",
                           title="Dataset containing information on all airports on ouraiports.com",
                           citation="OurAirports.com, Megginson Technologies Ltd.",
                           name="airports",
                           retriever_minimum_version="2.0.dev",
                           urls={u'regions': u'http://ourairports.com/data/regions.csv', u'airports': u'http://ourairports.com/data/airports.csv', u'countries': u'http://ourairports.com/data/countries.csv', u'runways': u'http://ourairports.com/data/runways.csv', u'airport_frequencies': u'http://ourairports.com/data/airport-frequencies.csv', u'navaids': u'http://ourairports.com/data/navaids.csv'},
                           keywords=[u'airports', u'aeroplanes', u'airplanes', u'frequencies', u'runways', u'navaids', u'countries', u'regions'],
                           retriever=True,
                           ref="http://ourairports.com/data/",
                           description="Dataset containing information on all airports on ourairports.com")