name: Avian Body Size Ecological Archives 2007
citation: Terje Lislevand, Jordi Figuerola, and Tamas Szekely. 2007. Avian body sizes in relation to fecundity, mating system, display behavior, and resource sharing. Ecology 88:1605.
description: A comprehensive compilation of data set on avian body sizes that would be useful for future comparative studies of avian biology.
shortname: AvianBodySize
tags: Taxon > Birds, Data Type > Compilation
ref: http://esapubs.org/archive/ecol/E088/096/
table: species, http://esapubs.org/archive/ecol/E088/096/avian_ssd_jan07.txt
*nulls: -999
