# Barnes et al. 2008, Ecological Archives, Retriever Script
name: Marine Predator and Prey Body Sizes (Ecological Archives 2008)
citation: C. Barnes et al. 2008. Predator and prey body sizes in marine food webs. Ecology 89:881.
shortname: MarineSize
tags: Taxon > Fish, Data Type > Compilation

table: main, http://www.esapubs.org/Archive/ecol/E089/051/Predator_and_prey_body_sizes_in_marine_food_webs_vsn3.txt
*nulls: 'n/a', '0.0000E+00'
