# basic information about the script
name: Biovolumes for freshwater phytoplankton - Colin et al. 2014
shortname: PhytoplankonBiovolume
citation: Colin T. Kremer, Jacob P. Gillette, Lars G. Rudstam, Pal Brettum, and Robert Ptacnik. 2014. A compendium of cell and natural unit biovolumes for >1200 freshwater phytoplankton species. Ecology 95:2984.
tags: Taxon > Phytoplankton, Data Type > Compilation

# tables
table: bvd_raw, http://esapubs.org/archive/ecol/E095/257/bvd_raw_052814.csv
*nulls: 'NA'
table: bvd_species_raw, http://esapubs.org/archive/ecol/E095/257/bvd_species_raw_030614.csv
*nulls: 'NA'
table: bvd_genus_raw, http://esapubs.org/archive/ecol/E095/257/bvd_genus_raw_030614.csv
*nulls: 'NA'
table: bvd_species_ag, http://esapubs.org/archive/ecol/E095/257/bvd_species_ag_030614.csv
*nulls: 'NA'
table: bvd_genus_ag, http://esapubs.org/archive/ecol/E095/257/bvd_genus_ag_030614.csv
*nulls: 'NA'
table: taxa_table, http://esapubs.org/archive/ecol/E095/257/taxa_table_030614.csv
*nulls: 'NA'
