name: Vegetation plots - del Moral, 2010
description: Roger del Moral. 2010. Thirty years of permanent vegetation plots, Mount St. Helens, Washington. Ecology 91:2185.
shortname: DelMoral2010
tags: Taxon > Plants

table: species_plot_year, http://esapubs.org/archive/ecol/E091/152/MSH_SPECIES_PLOT_YEAR.csv
table: structure_plot_year, http://esapubs.org/archive/ecol/E091/152/MSH_STRUCTURE_PLOT_YEAR.csv
table: species, http://esapubs.org/archive/ecol/E091/152/MSH_SPECIES_DESCRIPTORS.csv
table: plots, http://esapubs.org/archive/ecol/E091/152/MSH_PLOT_DESCRIPTORS.csv
