
# basic information about the script
name: Biomass and Its Allocation in Chinese Forest Ecosystems - Luo, et al., 2014
shortname: CForBioData
citation: Yunjian Luo, Xiaoquan Zhang, Xiaoke Wang, and Fei Lu. 2014. Biomass and its allocation in Chinese forest ecosystems. Ecology 95:2026.
tags: allocation > biomass > China > climate > forest type > necromass > stand structure

# tables
table: biomass, http://esapubs.org/archive/ecol/E095/177/CForBioData_v1.0.txt
*nulls: 'NA' 
