# basic information about the script
name: Antarctic Site Inventory breeding bird survey data, 1994-2013
shortname: ArcticBreedBird
description: Heather J. Lynch, Ron Naveen, and Paula Casanovas. 2013. Antarctic Site Inventory breeding bird survey data, 1994–2013. Ecology 94:2653.
tags: Taxon > Birds

# tables
table: species, http://esapubs.org/archive/ecol/E094/243/Antarctic_Site_Inventory_census_data_1994_2012.csv