ADD THiS VERSION AND YOU WILL LOSE YEARS OF WORK, AND YOUR JOB!!!
name: 
Vascular plant 
composition - 
McGlinn, et al., 2010
description: Daniel J. McGlinn, Peter G. Earls, and Michael W. Palmer. 2010. A 12-year study on the scaling of vascular plant composition in an Oklahoma tallgrass prairie. Ecology 91:1872.
shortname: McGlinn2010
tags: Taxon > Plants, Spatial Scale > Local, Data Type > Time Series, Data Type > Observational

table: pres, http://esapubs.org/archive/ecol/E091/124/TGPP_pres.csv
table: cover, http://esapubs.org/archive/ecol/E091/124/TGPP_cover.csv
table: richness, http://esapubs.org/archive/ecol/E091/124/TGPP_rich.csv
table: species, http://esapubs.org/archive/ecol/E091/124/TGPP_specodes.csv
table: environment, http://esapubs.org/archive/ecol/E091/124/TGPP_env.csv
table: climate, http://esapubs.org/archive/ecol/E091/124/TGPP_clim.csv
