name: North Carolina forest plants (Ecological Archives 2007)
shortname: Palmer2007
citation: Michael W. Palmer, Robert K. Peet, Rebecca A. Reed, Weimin Xi, and Peter S. White. 2007. A multiscale study of vascular plants in a North Carolina Piedmont forest. Ecology 88:2674.
tags: Taxon > Plants, Spatial Scale > Local, Data Type > Time Series, Data Type > Observational
ref: http://esapubs.org/archive/ecol/E088/162/

table: pres, http://esapubs.org/archive/ecol/E088/162/Oosting_pres2.txt
table: species, http://esapubs.org/archive/ecol/E088/162/species_codes.txt
replace: check, checkrec
table: trees, http://esapubs.org/archive/ecol/E088/162/Oosting_Trees_1998.txt
*nulls: '.', ''
table: env, http://esapubs.org/archive/ecol/E088/162/Oosting_env.txt
