name: Sonoran Desert Perennials
description: Susana Rodriguez-Buritica, Helen Raichle, Robert H. Webb, Raymond M. Turner, and D. Lawrence Venable. 2013. One hundred and six years of population and community dynamics of Sonoran Desert Laboratory perennials. Ecology 94:976.
shortname: SonoranPerennials
tags: Taxon > Plants

table: Plots, http://esapubs.org/archive/ecol/E094/083/Plots.csv
*nulls: 'NA'
table: Plot_corners, http://esapubs.org/archive/ecol/E094/083/Plot_corners.csv
*nulls: 'NA'
table: Species, http://esapubs.org/archive/ecol/E094/083/Species.csv
*nulls: 'NA'
table: Seedling_counts, http://esapubs.org/archive/ecol/E094/083/Seedling_counts.csv
*nulls: 'NA'
table: Count1906, http://esapubs.org/archive/ecol/E094/083/Count1906.csv
*nulls: 'NA'
table: SMCover, http://esapubs.org/archive/ecol/E094/083/SMCover.csv
*nulls: 'NA'
table: SMDensity, http://esapubs.org/archive/ecol/E094/083/SMDensity.csv
*nulls: 'NA'
table: Stake_info, http://esapubs.org/archive/ecol/E094/083/Stake_info.csv
*nulls: 'NA', 'nd'
table: Photo_info, http://esapubs.org/archive/ecol/E094/083/Photo_info.csv
*nulls: 'NA'