name: Mammal Community DataBase (Ecological Archives 2011)
citation: Katherine M. Thibault, Sarah R. Supp, Mikaelle Giffin, Ethan P. White, and S. K. Morgan Ernest. 2011. Species composition and abundance of mammalian communities. Ecology 92:2316.
shortname: MCDB
tags: Taxon > Mammals, Spatial Scale > Global, Data Type > Observational
url: http://esapubs.org/archive/ecol/E092/201/

table: communities, http://esapubs.org/archive/ecol/E092/201/data/MCDB_communities.csv
table: references, http://esapubs.org/archive/ecol/E092/201/data/MCDB_references.csv
table: sites, http://esapubs.org/archive/ecol/E092/201/data/MCDB_sites.csv
table: species, http://esapubs.org/archive/ecol/E092/201/data/MCDB_species.csv
table: trapping, http://esapubs.org/archive/ecol/E092/201/data/MCDB_trapping.csv