name: Mammal and Bird foraging attributes -- Wilman, et al., 2014

description: characterization of Species by physiological, behavioral, and ecological attributes that are subjected to varying evolutionary and ecological constraints and jointly determine their role and function in ecosystems.
citation: Hamish Wilman, Jonathan Belmaker, Jennifer Simpson, Carolina de la Rosa, Marcelo M. Rivadeneira, and Walter Jetz. 2014. EltonTraits 1.0: Species-level foraging attributes of the world's birds and mammals. Ecology 95:2027. 
shortname: EltonTraits
tags: Taxon > Mammals, Taxon > Birds, Data Type > Compilation
citation

table: BirdFuncDat, http://esapubs.org/archive/ecol/E095/178/BirdFuncDat.txt
table: MammFuncDat, http://esapubs.org/archive/ecol/E095/178/MamFuncDat.txt
table: BirdCitations, http://esapubs.org/archive/ecol/E095/178/BirdFuncDatSources.txt
table: MammCitations, http://esapubs.org/archive/ecol/E095/178/MamFuncDatSources.txt
