name: MammalDIET
description: Kissling WD, Dalby L, Flojgaard C, Lenoir J, Sandel B, Sandom C, Trojelsgaard K, Svenning J-C (2014) Establishing macroecological trait datasets: digitalization, extrapolation, and validation of diet preferences in terrestrial mammals worldwide. Ecology and Evolution, online in advance of print. doi:10.1002/ece3.1136
shortname: MammalDIET
tags: Taxon > Mammals, Data Type > Compilation

table: diet, http://datadryad.org/bitstream/handle/10255/dryad.64565/MammalDIET_v1.0.txt
*nulls: 'NA'
