name: USDA plants
description: Plant taxonomy system available on the USDA plants site.
shortname: PlantTaxonomy
tags: Taxon > Plants, Data Type > Taxonomy
url: http://plants.usda.gov

table: PlantTaxonomy, http://plants.usda.gov/java/downloadData?fileName=plantlst.txt&static=true
*column: record_id, pk-auto
*column: symbol, char, 7
*column: synonym_symbol, char, 7
*column: scientific_name, char
*column: common_name, char, 50
*column: family, char, 30
*do_not_bulk_insert: True
